# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name (e.g. Elie Fute)', max_length=20)),
                ('matricule', models.CharField(help_text='Enter a matricule (e.g. AD123  etc.)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('election_type', models.CharField(help_text='select election type (e.g. faculty, department)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a department name (e.g. electrical and electronics engineering, computer engineering etc.)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField()),
                ('election_type', models.CharField(choices=[('FA', 'Faculty'), ('DE', 'Department')], max_length=10)),
                ('academicyr', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Exco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a post (e.g. departmental president, faculty president  etc.)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(help_text='Enter a student name (e.g. Ytembe Dankam Therese  etc.)', max_length=50)),
                ('matricule', models.CharField(help_text='Enter a matricule (e.g. FE14A221  etc.)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Department')),
            ],
        ),
        migrations.AddField(
            model_name='facultyelection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Post'),
        ),
        migrations.AddField(
            model_name='facultyelection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Student'),
        ),
        migrations.AddField(
            model_name='exco',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Post'),
        ),
        migrations.AddField(
            model_name='exco',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Student'),
        ),
        migrations.AddField(
            model_name='departmentelection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Post'),
        ),
        migrations.AddField(
            model_name='departmentelection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Student'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Department'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='matricule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Student'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Post'),
        ),
    ]
