# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='matricule',
            new_name='student',
        ),
    ]
