# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180611_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='election',
            name='academicyr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='why_apply',
            field=models.TextField(default='I promise to look for internship', help_text='Enter reasons why you choose to be an exco'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='why_vote',
            field=models.TextField(default='I promise to look for internship', help_text='Enter reasons why we should vote for you'),
        ),
        migrations.AddField(
            model_name='election',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(help_text='Enter a student name (e.g. Dankam Celestin etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(help_text='Enter a student name (e.g. Ytembe etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(help_text='Enter a student name (e.g. Dankam Therese etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mothername',
            field=models.CharField(help_text='Enter a student name (e.g. Dankam Pauline etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election_type',
            field=models.CharField(choices=[('FA', 'Faculty'), ('DE', 'Department')], max_length=10),
        ),
        migrations.AlterField(
            model_name='election',
            name='duedate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
