# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20180615_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(help_text='(e.g. 1997-02-07)', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(help_text='Choose a department', on_delete=django.db.models.deletion.CASCADE, to='elections.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathername',
            field=models.CharField(help_text="Father's name (e.g. Dankam Celestin etc.)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(help_text='Your first name (e.g. Ytembe etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(help_text='Your other names (e.g. Dankam Therese etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(help_text='Your matricule (e.g. FE14A221  etc.)', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothername',
            field=models.CharField(help_text="Mother's name (e.g. Dankam Pauline etc.)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, help_text='upload a profile pic', upload_to='profile_images'),
        ),
    ]
